- name: variable
  hosts: local
  connection: local
  vars: # PLAY level variables
    COURSE: "devops with aws"
    DURATION: 120hrs
    TRAINER: sivakumar
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }},trainer {{ TRAINER }}"