- name: variable
  hosts: local
  connection: local
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }},trainer {{ TRAINER }}"