- name: variable
  hosts: local
  connection: local
  # vars: # PLAY level variables
  #   GREET: "PLAY"
  vars_files:
  - course.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: enter the value
  #   private: false
  tasks:
  - name: print the variable
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "hello from {{ GREET }}"

#1. command line or args
#2. task level
#3.prompt