- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-0eae5bf6ce05c9c9f
    sg_id: sg-0d21df297f0010e9f
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend 
  tasks:
  - name: install aws python libraries 
    ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore 
  - name: create ec2 instances 
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"